Fix PHP Warning:  Illegal string offset 'id_category_default'
PrestaShop/dashproducts pull request #47
Opened 2023-03-10 19:46 UTC by lea-BMS

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Correctly handles the varying types of returned value from `Product->getDefaultCategory()`<br/>Because `Product->getDefaultCategory()` returns either an `array` or an `int` \(or a `false\|string` with older PrestaShop versions prior to https://github.com/PrestaShop/PrestaShop/pull/26478 's patch\), the returned value type must be tested and handled accordingly or; php will raise a `PHP Warning:  Illegal string offset 'id_category_default'`, and more problematically use the wrong default category id value.
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | Using PHP 7.2 or above, access to the Backoffice's Dashboard and, see no more `PHP Warning:  Illegal string offset 'id_category_default'`

2023-03-13 08:22 UTC, nicosomb approved these changes
seems ok for me

2023-03-15 08:35 UTC, kpodemski commented
Hello @lea-BMS 

Thanks for submitting the pull request! First of all, there are some coding standards issues after your changes. You can solve them by running PHP-CS-Fixer locally, here's an instruction:
https://github.com/prestashop/php-dev-tools/#php-cs-fixer-1


Secondly, PHPStan complains, but it seems it's wrong, so you can add a new rule:

`    - '#Parameter \#1 \$idCategory of class Category constructor expects null, int given#'`

to this file: https://github.com/PrestaShop/dashproducts/blob/dev/tests/phpstan/phpstan-1.7.6.neon

2023-03-15 08:35 UTC, kpodemski requested changes
Comment above.

2023-03-22 10:45 UTC, matthieu-rolland reviewed
I fixed the cs fixer issue and added the phpstan conf suggested by @kpodemski , you still have a phpstan issue line 225 on your ternary condition

@lea-BMS maybe you should try not doing a ternary and casting the variable in a proper condition, I'm not 100% sure it will make phpstan happy but I'm guessing the syntax is a bit exotic for him (ternary inside an int cast)

2023-03-29 06:31 UTC, kpodemski commented
Hi @lea-BMS 

Do you plan to continue with this PR? :)

2023-04-24 10:57 UTC, kpodemski commented
Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

2023-04-24 10:57 UTC, closed without merging