Fix category retrive for bestsellers
PrestaShop/dashproducts pull request #50
Opened 2023-04-11 19:11 UTC by mflasquin

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fix category retrive for bestsellers
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/31321
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/31321

2023-04-12 09:21 UTC, matks approved these changes

2023-04-12 09:33 UTC, Hlavtox requested changes
Some performance optimization.

2023-04-12 09:33 UTC, Hlavtox commented on dashproducts.php
> +            $category = new Category($productCategoryId, $this->context->language->id);
```suggestion
            $productCategoryId = $product_obj->getDefaultCategory();
            if (is_array($productCategoryId) && isset($productCategoryId['id_category_default'])) {
                $productCategoryId = $productCategoryId['id_category_default'];
            }
            $category = new Category($productCategoryId, $this->context->language->id);
```
Saves 3 database queries

2023-04-14 09:11 UTC, djoelleuch commented
Hello @mflasquin  , 

There is a return of review , so we can't test this PR . 
Can you please check this  [comment](https://github.com/PrestaShop/dashproducts/pull/50#pullrequestreview-1380913474) 

Thank you !

2023-04-21 10:14 UTC, florine2623 approved these changes
Hello @mflasquin ,

It works as expected !

Before :
<img width="903" alt="Screenshot 2023-04-21 at 12 12 16" src="https://user-images.githubusercontent.com/16019289/233611237-98168fc6-1bde-44fa-998d-1ac3825f7cea.png">


After :
<img width="902" alt="Screenshot 2023-04-21 at 12 13 28" src="https://user-images.githubusercontent.com/16019289/233611256-d17d1f49-51fa-48a6-9280-c470bc032052.png">

It is QA ✅ 
Thanks!

2023-04-21 10:21 UTC, merged

2023-04-21 10:21 UTC, Hlavtox commented
Good job @mflasquin and @florine2623! :-)

2023-05-05 09:44 UTC, PeNov commented
Hello,
Thank you for this fix.
Error `(PHP Notice:  Trying to access array offset on value of type int in /home/www/domain.cz/www/domain.cz/modules/dashproducts/dashproducts.php on line 224)` from the web server log gone.

But still is present this error `PHP Warning:  Invalid argument supplied for foreach() in /home/www/domain.cz/www/domain.cz/modules/dashproducts/dashproducts.php on line 219`

If I set period from this month 1.5.2023 - 5.5.2023 - works.

If I set period from 2023-04-24 to 2023-05-05 - showing nothing.
![image](https://user-images.githubusercontent.com/38213520/236425145-94468ad3-e1c6-4dc2-b061-92c4696d89f9.png)

Thank you
Best regards
PN